name: My Initial workflow
on:
  push:
    branches:
      - 'master'
  workflow_dispatch:
    inputs:
      KushAshtu: 
        description: 'Kush A'
        required: true


jobs:
  testing:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - name: Getting Code
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci
      - name: Running Steps
        run: npm run test
  report:
    runs-on: ubuntu-latest
    needs: testing
    if: ${{ always()}}
    steps:
      - name: Run Report
        run: echo "${{ needs.testing.result }}"

# it will run now