name: My Initial workflow
on: [push, workflow_dispatch]

jobs:
  testing:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - name: Getting Code
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ca
      - name: Running Steps
        run: npm run test
  report:
    runs-on: ubuntu-latest
    needs: testing
    if: failure()
    steps:
      - name: Run Report
        run: echo "${{ needs.testing.result }}"
